name: vietqr_flutter
description: "Generator VietQR not using api."
version: 1.0.0
homepage: https://github.com/daturit/vietqr_flutter

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:


